### ISSUE TITLE
Tech to use for Unit testing and test coverage checks in Golang.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-api#3]
Find a test coverage checks tool that tells us if everything has unit tests or not and help use write better tests.

Expected result:
1- Documentaiton of how to do unit testin (can a short explanaton with links to specifics written in other places or wrtten by your self)
2- Possible test coverage libraries/framewords to use. Recommend and explain one and test and how results; document same way as point 1.

**Comment by ezielramos** [comment]
Unit Test in Golang:

5 of the most popular library for unit testing are:
Testify; GoConvey; Ginkgo; httpexpect; Gomega

1*Go standard library: The "testing" package
Unlike most other languages, Go has a built-in test runner and framework for standard language tooling. 
The easiest way to run unit tests for your project is using a command like go test ./... from the command line. 
Running this command will discover and run any tests within your current directly or their subdirectories.

Tests must be in files separate from your main package code and end with the suffix _test.go. 
A test function is identified by starting with func Test .

to run the tests:	 go test ./...

Golang test tool provides 3 functions :
a) Test function.

b) Benchmark function: In developing software, sometimes we have a different way with 
our partners or maybe we have many solutions to solve one problem. How can we measure 
which is the best solution? One of the answers is to test the performance from all of 
our solutions and chose the fastest.

c) Example function.
Example function is a little same with the Test function, that is to make sure that 
our program runs as we expected.
The Example function is intended for programmers who want to quickly create unit tests. 
The example unit test function automatically compares the standard output print (fmt) in 
golang with our output comment, so we don't have to create check expected logic.
Because the syntax doesn’t require additional libraries and we don’t need to make logic
 to match the results obtained with expectations, making unit tests can be done faster.
There are 2 advantages for creating example unit test :
Faster to create a unit test. Because the code in the unit test is less than usual, 
so the programmer can faster to make a unit test.
Easy to do experimentations

>>The package does not support assertions or other testing helper functions, as the 
development team believes implementing these features would add too much complexity. 
To counter the repetitiveness of writing tests without assertions and helper functions, 
they suggest using table-driven tests.

Reference:
https://speedscale.com/2022/02/22/golang-testing-frameworks/
https://bmuschko.com/blog/go-testing-frameworks/
https://medium.com/tunaiku-tech/unit-test-in-golang-57a2a896d90d
https://www.pullrequest.com/blog/unit-testing-in-go/

**Comment by ezielramos** [comment]
# Test coverage checks tool
