### ISSUE TITLE
Store Glacier data to access upload file

### ISSUE THREAD

**Issue by alvaldes** [Sesame-Disk/cool-storage-api#31]
Objective: Get the necessary data and save it in the DB to access Glacier files.
Depends On: https://github.com/Sesame-Disk/cool-storage-api/issues/35

Story Points: 3

**Comment by abelguzman** [comment]
This information is what will allow us to know if the files were from user A or B and what path to retrieve. also because of the nature of AWS Glacier, the files once stored are not directly available, so there are stages here. you store it, then when you need it you request it and AWS starts working on it, meanwhile you just need to check from time to time if already available or not. Then once aws says is available, you can retrieve it. the logic will have more considerations, but those are the main-ones I see.

**Comment by alvaldes** [comment]
closed on 64190891d72b1ce55f81e8d59c2f73ae6f6d8819
